version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTRGRES_DB: FastAPI_test_app